// Encoding/decoding
function Encode64: string; inline;
function Decode64: string; inline;
function TryDecode64(out Decoded: string): Boolean; inline;
function HTMLEncode: string; inline;
function HTMLDecode: string; inline;
function URLEncode: string; inline;
function URLDecode: string; inline;
function PercentEncode: string; inline;
function PercentDecode: string; inline;
function FormURLEncode: string; inline;
function FormURLDecode: string; inline;
function HexEncode: string; inline;
function HexDecode: string; inline;
function TryHexDecode(out Decoded: string): Boolean; inline;
